services:
  - type: web
    name: devtracker-backend
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health/ping
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGINS
        sync: false
